### ISSUE TITLE
BaseResponse注解不加也行啊

### ISSUE THREAD

**Issue by webcat007** [spring-based-solutions/spring-web-unified-response-demo#1]

**Comment by ruanjiehui** [comment]
不明白你的标题的意思，是指的是不使用@BaseResponse注解也可以让统一响应体生效吗？

**Comment by webcat007** [comment]
是的    我压根没写BaseResponse注解接口     同样能统一返回

**Comment by ruanjiehui** [comment]
你说的问题我不知道怎么重现，可以说一下重现的步骤吗？ @webcat007

**Comment by LinScript** [comment]
有个问题想请教下，https://programmer.ink/think/springboot-unified-response-body-solution.html 这个文章是您写的吗，能加下你吗

**Comment by ruanjiehui** [comment]
@LinScript 你可以加一下我的QQ：641439949

**Comment by LinScript** [comment]
@ruanjiehui  收到
